
$(document).ready(function () {
    
    //$("#scan").on("click", async function () {
    $(".btnScan").on("click", async function () {
        var gustProfileId = $(this).val();
        $('#guestProfileId').val(gustProfileId);
       // if ($('#DocumentTypeId option:selected').attr('data-FolderName')) {
        if ($('#DocumentProcessWiseDocumentId option:selected').data('folder-name')) {
            ShowLoader();
            
            const { result, message, data, error } = await MyScan.scan();
            var a = data[0];
            var b = JSON.stringify(a.ocrText);
            var c = JSON.parse(b);

            console.log(result);
            console.log(data);
            console.log(error);
            
            try {
                if (result) {
                    HideLoader();
                    data.map((file) => {
                        const { fileName, base64 } = file;

                        $("#ScannedDocument").attr("src", base64);
                        $("#ScannedDocumentBase64").val(base64);
                    });
                } else {
                    console.log(error);
                    HideLoader();
                }

            } catch (e) {
                HideLoader();
                console.warn(e);
                $(".loading-mask").addClass("hide");
                //const { error = "unknown" } = e;
                const { error = "The passport scanner was unable to capture the image properly. This error was generated by the passport scanner. Could you please ensure the Driving License /NIC is properly positioned in the scanner and try again?" } = e;
                alert(`Scan error: ${error}`);
            }
            
            
        } else {

            try {
                //$(".loading-mask").removeClass("hide");
                const { result, message, data, error } = await MyScan.scan();

                var a = data[0];
                var b = JSON.stringify(a.ocrText);
                var c = JSON.parse(b);


                if (result) {
                    
                    data.map((file) => {

                        console.log(file);

                        const { fileName, base64 } = file;
                        $('#passportDetailsConfirmationForm').show();
                        $("#ScannedImage").attr("src", base64);

                        $("#imageStringbase64").val(base64);

                        var passport = {
                            Angle: c.Angle,
                            Birthday: c.Birthday,
                            Checksum: c.Checksum,
                            Dateofexpiry: c.Dateofexpiry,
                            DocumentNo: c.DocumentNo,
                            Familyname: c.Familyname,
                            Givenname: c.Givenname,
                            IssueState: c.IssueState,
                            //MRTDs: c.MRTDs,
                            Nationality: c.Nationality,
                            NativeName: c.NativeName,
                            PersonalNo: c.PersonalNo,
                            Sex: c.Sex,
                            Type: c.Type
                            //Image: base64
                            //'data:image/jpeg;base64,' + data.ImageString
                        };

                        //console.log(passport);

                        $('#Familyname').val(c.Familyname);
                        $('#Nationality').val(c.Nationality);
                        $('#Sex').val(c.Sex);
                        $('#DocumentNo').val(c.DocumentNo);
                        $('#Givenname').val(c.Givenname);
                        $('#IssueState').val(c.IssueState);
                        //$("#ScannedImage").attr('src', 'data:image/jpeg;base64,' + formattedJson.ImageString);


                        $('#DocType').val(c.Type);
                        $('#Angle').val(c.Angle);
                        $('#MRTDs').val(c.MRTDs);
                        $('#NativeName').val(c.NativeName);
                        $('#Checksum').val(c.Checksum);
                        //$('#Dateofexpiry').val(c.Dateofexpiry);
                        //$('#Birthday').val(c.Birthday);

                        var unformattedBDay = c.Birthday.toString();
                        var unformattedExpirey = c.Dateofexpiry.toString();
                        console.log(unformattedBDay);
                        console.log(unformattedExpirey);

                        // Convert string to date object - Birthday
                        var birthYear = parseInt(unformattedBDay.substring(0, 2)); // Extract the year
                        var birthMonth = parseInt(unformattedBDay.substring(2, 4)) - 1; // Extract the month (zero-based)
                        var birthDay = parseInt(unformattedBDay.substring(4, 6)); // Extract the day

                        // Adjust the birth year to the correct century
                        var currentYear = new Date().getFullYear() % 100; // Get the last two digits of the current year
                        var birthCentury = Math.floor(new Date().getFullYear() / 100); // Get the century
                        if (birthYear > currentYear) {
                            birthCentury -= 1; // If birth year is greater than current year, adjust the century
                        }
                        var birthDate = new Date(birthCentury * 100 + birthYear, birthMonth, birthDay);

                        // Convert string to date object - Expiry Date
                        var expiryYear = parseInt(unformattedExpirey.substring(0, 2)); // Extract the year
                        var expiryMonth = parseInt(unformattedExpirey.substring(2, 4)) - 1; // Extract the month (zero-based)
                        var expiryDay = parseInt(unformattedExpirey.substring(4, 6)); // Extract the day

                        // Adjust the expiry year to the correct century
                        var expiryCentury = Math.floor(new Date().getFullYear() / 100); // Get the century
                        if (expiryYear > currentYear && expiryYear - currentYear > 30) {
                            expiryCentury -= 1; // If expiry year is greater than current year and the difference is more than 30 years, adjust the century
                        } else if (currentYear - expiryYear > 70) {
                            expiryCentury += 1; // If the expiry year is more than 70 years ago, it's likely in the previous century
                        }
                        var expiryDate = new Date(expiryCentury * 100 + expiryYear, expiryMonth, expiryDay);

                        // Format date to DD/MM/YYYY
                        var formatDate = function (date) {
                            var dd = String(date.getDate()).padStart(2, '0');
                            var mm = String(date.getMonth() + 1).padStart(2, '0'); //January is 0!
                            var yyyy = date.getFullYear();
                            return dd + '/' + mm + '/' + yyyy;
                        };

                        // Set formatted dates to input fields
                        $('#Birthday').val(formatDate(birthDate));
                        $('#Dateofexpiry').val(formatDate(expiryDate));




                        //$.ajax({
                        //    url: '/reservation/reservations/SavePassportOnHotelResWeb_PassportScan',
                        //    dataType: 'json',
                        //    method: 'POST',
                        //    data: { guestId: gustProfileId},
                        //    beforeSend: function () { },
                        //    complete: function () { },
                        //    success: function (data) {
                        //        debugger;
                        //        ShowSuccessMessage('AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA.');
                        //        //if (data.DocumentNo == null) {
                        //        //    //ShowErrorMessage('Sorry there is an error in scanning the passport.');
                        //        //    ShowWarningMessage('Scanner busy. Please try again after 10 seconds.');
                        //        //} else {
                        //        //    ShowPassportDetails(data, uUid);
                        //        //}
                        //    },
                        //    error: function (data) {
                        //        ShowErrorMessage('Sorry there is an error in scanning the passport.');
                        //    }
                        //});

                    });
                    //}

                } else {
                    console.log(error);
                }



            } catch (e) {
                console.warn(e);
                $(".loading-mask").addClass("hide");
                //const { error = "unknown" } = e;
                const { error = "The passport scanner was unable to capture the image properly. This error was generated by the passport scanner. Could you please ensure the Passport is properly positioned in the scanner and try again?" } = e;
                alert(`Scan error: ${error}`);
            }
        }

    });

    async function init() {
        try {
            debugger;
            //alert('aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa');
            await MyScan.connect({ ip: "127.0.0.1", port: "17778" });
            //await MyScan.connect({ ip: "https://localhost/", port: "17778" });
            await MyScan.init();

            const { data: optionData } = await MyScan.getDeviceList();
            const { options, groupOptions } = optionData;
            // check scanner is exist
            if (options.length < 1) {
                throw new Error({ error: "Scanner not detected." });
            }
            // default first device.
            const { deviceName = "", source = {} } = options[0];
            const { value: sourceAry = [] } = source;
            if (sourceAry.length < 1) {
                throw new Error({ error: "Scanner model identification failed." });
            }
            const scannerConfig = {
                deviceName: deviceName, // first device
                source: sourceAry[0], // paper orientation
                paperSize: "A4",
                resolution: 300, // dpi
                mode: "color",
                brightness: 0,
                contrast: 0,
                quality: 75,
                swcrop: true, // auto crop
                swdeskew: true, // auto deskew
                recognizeType: "passport",
                recognizeLang: "en",
            };

            console.log(scannerConfig);
            await MyScan.setScanner(scannerConfig);

            $("#status").removeClass("connect-color").addClass("success-color");
            $("#status").text("Connection successful.");
            $(".btnScan").prop("disabled", false);
        } catch (e) {
            HideLoader();
            console.warn(e);
            const { error = "unknown" } = e;
            $("#status").removeClass("connect-color").addClass("failure-color");
            $("#status").text("Connection failed");
            alert(`Scanner initialization error: ${error}`);
        }
    }

    const MyScan = new WebFxScan();
    init();

});
